version: "3.9"
services:
  minecraft-server:
    image: itzg/minecraft-bedrock-server
    env_file:
      - .env
    ports:
      - 19132:19132/udp
    healthcheck:
      test: ["CMD", "mc-monitor", "status-bedrock", "127.0.0.1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    volumes:
      - ${MAP_PATH:-./data}:/data
  web-bedrock-viz:
    build: ../..
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ${MAP_PATH:-./data}/worlds/${LEVEL_NAME:-world}:/source
      - ${MAP_HTML:-./html}:/usr/share/nginx/html
